language: node_js
dist: trusty
node_js:
  - node
before_script:
  - sleep 15
services: mongodb
install:
  - npm install
before_script:
  - mongo --version
  - node --version
  - npm --version
after_success: npm run coverage
