language: node_js
node_js:
  - node
install:
- npm install
addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell
before_script:
  - sleep 15
before_script:
  - mongo --version
  - node --version
  - npm --version
after_success: npm run coverage
